[tool.poetry]
name = "function-sampler"
version = "0.1.0"
description = "Function calling Logit Sampler"
authors = ["Nathan Hoos <thwackyy.y@gmail.com>"]
license = "Apache 2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
transformers = "^4.38.2"
pydantic = "^2.6.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.packages]
include = [{ from = "function_sampler", include = ["**/*"] }]
